{{- if or .Values.checks .Values.informer.upstreams .Values.configSources.downstreams }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthetic-checker.fullname" . }}
  labels:
    {{- include "synthetic-checker.labels" . | nindent 4 }}
    app: synthetic-checker
type: Opaque
data:
  "checks.yaml": {{ include "synthetic-checker.config" . | b64enc | quote }}
{{- end }}
{{- if .Values.rbacProxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "synthetic-checker.fullname" . }}-rbac-proxy
data:
  config-file.yaml: |+
    authorization:
      resourceAttributes:
        namespace: default
        apiVersion: v1
        resource: services
        subresource: proxy
        name: kube-rbac-proxy
{{- end }}
