{{- if or .Values.checks .Values.informer.upstreams .Values.configSources.downstreams }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthetic-checker.fullname" . }}
  labels:
    {{- include "synthetic-checker.labels" . | nindent 4 }}
    app: synthetic-checker
type: Opaque
data:
  "checks.yaml": {{ include "synthetic-checker.config" . | b64enc | quote }}
{{- end }}
