{{- if .Values.nodepinger }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "synthetic-checker.fullname" . }}-pinger
  labels:
    {{- include "synthetic-checker.labels" . | nindent 4 }}
    app: nodepinger
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "synthetic-checker.selectorLabels" . | nindent 6 }}
      app: nodepinger
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synthetic-checker.selectorLabels" . | nindent 8 }}
        app: nodepinger
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "synthetic-checker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - start
            - -p {{ .Values.service.containerPort }}
            - -F {{ .Values.statusCodes.failed }}
            - -D {{ .Values.statusCodes.degraded }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          secret:
            secretName: {{ include "synthetic-checker.fullname" . }}-pinger
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthetic-checker.fullname" . }}
  labels:
    {{- include "synthetic-checker.labels" . | nindent 4 }}
    app: nodepinger
type: Opaque
dataString:
  "checks.yaml": |
    k8sPings:
      nodepinger:
        labelSelector: "{{ (include "synthetic-checker.selectorLabels" .) | replace ": " "=" | replace "\n" "," }},app=nodepinger"
        interval: 30s
        port: {{ .Values.service.containerPort }}
        namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synthetic-checker.fullname" . }}-pinger
  labels: {{- include "synthetic-checker.labels" . | nindent 4 }}
    app: nodepinger
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "synthetic-checker.selectorLabels" . | nindent 4 }}
    app: nodepinger
{{- end }}
