{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synthetic-checker.serviceAccountName" . }}
  labels:
    {{- include "synthetic-checker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.rbacProxy.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthetic-checker.serviceAccountName" . }}-krp
  annotations:
    kubernetes.io/service-account.name: {{ include "synthetic-checker.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
